### ISSUE TITLE
the issue about the segment_anything

### ISSUE THREAD

**Issue by BigTree765** [yxKryptonite/OpenFMNav#1]
When I run the code, I face the issue about  cannot import name 'build_sam_hq' 

```python
>>> import segment_anything
>>> from segment_anything import SamPredictor
>>> from segment_anything import sam_model_registry
>>> from segment_anything import build_sam_hq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'build_sam_hq' from 'segment_anything'
```

**Comment by yxKryptonite** [comment]
Please checkout [Grounded-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything) to install segment_anything and groundingdino.

**Comment by zwhy66** [comment]
> 请查看 [Grounded-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything) 以安装 segment_anything 和接地 dino。

我想请问几个问题，复现的时候具体用到了哪些模型。GPT4？ 代码中api-key 是不是只需要换一下llm.py中的？咋们的实验跑了2000轮吗，跑2000论的话需要多少时间？如果方便的话我想加一下您的vx聊一下。我的vx：17303470305.不方便的话 恳请您回复一下我的疑问
