### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by Rh-Dang** [yxKryptonite/OpenFMNav#3]
Which habitat dataset version should I download? v0.1 or v0.2 ?  looking forward to your reply

**Comment by yxKryptonite** [comment]
Hi, we use v0.2 version.

**Comment by Rh-Dang** [comment]
Thank you very much for your reply. Could you please provide the specific code for downloading the data set? Is hm3d_minival_v0.2 enough? Or need other documents?

**Comment by yxKryptonite** [comment]
Hi, we downloaded the dataset from [here](https://github.com/matterport/habitat-matterport-3dresearch). And you will also need val split for evaluation.

**Comment by Rh-Dang** [comment]
I have downloaded all the minival, train and val files for v0.2, but now there are only two folders, scene datasets and versioned data. Where can the objectgoal_hm3d folder and the other two files be downloaded?

**Comment by yxKryptonite** [comment]
Looks like you've already fixed the problem, closing the issue now.

**Comment by zhouak47** [comment]
> Thank you very much for your reply. Could you please provide the specific code for downloading the data set? Is hm3d_minival_v0.2 enough? Or need other documents?

Could you tell me which package i should download in the HM3D dataset and how to prepare the data? Thanks
