### ISSUE TITLE
load file error

### ISSUE THREAD

**Issue by Rh-Dang** [yxKryptonite/OpenFMNav#4]
Hi！！I encountered the following problem while running the project.
"""""""""""""""""""""""""""""""""""""""
final text_encoder_type: bert-base-uncased
=====> [ERROR]: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'., sleep for 20s...
""""""""""""""""""""""""""""""""""""""
It seems that I can't connect to the huggingface website, I want to download these files offline, can you give me some help? For example, which web do I need to go, what files do I need to download and where do I need to put them?

**Comment by yxKryptonite** [comment]
2 solutions:

1. use a proxy (e.g. clash)
2. check out [this blog](https://blog.csdn.net/ewen_lee/article/details/130992494) for huggingface model deployment

**Comment by Rh-Dang** [comment]
Thank you very much for your answer!!
