### ISSUE TITLE
Real robot code

### ISSUE THREAD

**Issue by dethresearcher** [yxKryptonite/OpenFMNav#7]
Hi!

Great work on the project. Would you be able to share the code for the real world robot experiments?

**Comment by yxKryptonite** [comment]
Hi, the detection, reasoning, mapping, etc. parts of the project are open-sourced. For TurtleBot control, you can check out [this repo](https://github.com/markwsilliman/turtlebot) for reference.

**Comment by dethresearcher** [comment]
Thank you for the quick reply! 

Currently the semantic mapping code in this repository is connected to Habitat, but I am interested in connecting it to ROS. I would be super grateful if you could provide some code for this (or perhaps email to me if it does not fit the scope of this repository).

**Comment by MengyangGao** [comment]
Any updates? I also want to implement in real world. From the paper, the team used RealSense SR300, but hasn’t shared any code of real world implementation in repo. 
My understanding of the perception part is:
Given the observations info(RGB, D, Pose) from habitat simulator, RGB is sent to DiscoverVLM for updating the goal list. RGB, D,  Pose are sent to PerceptVLM for segmentation and create semantic map(VSSM). 
I know that we should use RGBD camera to get RGB and D. As the pose is generated from habitat simulator, we should use some SLAM/VIO system to get pose estimation. 
The point is we miss:
1. Details of using RGBD camera to replace the habitat observation. 
2. Details of using SLAM/ VIO system and camera to replace the ‘sensor_pose’ in habitat simulator.
Some code related might be ‘obs, infos = even.reset()’ in ‘main.py’.  The construct_env function in ‘envs/habitat/__init__.py’

Any updates would be appreciated!

**Comment by zwhy66** [comment]
> 有更新吗？我也想在现实世界中实现。从论文中，该团队使用了 RealSense SR300，但没有在存储库中共享任何实际实现的代码。我对感知部分的理解是：给定来自栖息地模拟器的观测信息（RGB、D、Pose），RGB 被发送到 DiscoverVLM 以更新目标列表。RGB、D、Pose发送到PerceptVLM进行分割，并创建语义图（VSSM）。我知道我们应该使用 RGBD 相机来获得 RGB 和 D。由于位姿是从栖息地模拟器生成的，因此我们应该使用一些 SLAM/VIO 系统来获得位姿估计。关键是我们错过了：
> 
> 1. 使用RGBD相机代替栖息地观测的细节。
> 2. 使用 SLAM/VIO 系统和摄像头替换栖息地模拟器中的“sensor_pose”的详细信息。一些相关的代码可能是 'main.py' 中的 'obs， infos = even.reset（）'。'envs/habitat/**init**.py' 中的 construct_env 函数
> 
> 任何更新将不胜感激！

您好，我是一个研究生。我想问一下和您讨论几个复现的openfmnav的问题，不知道您方便不。方便的话可以加一下我的vx：17303470305
