### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by zhouak47** [yxKryptonite/OpenFMNav#9]
Thanks for your great job.I have some trouble when i prepare the data.I do not know where can I download these files (matterport_category_mappings.tsv and  object_norm_inv_perplexity.npy). And I am confused about the files in the versioned_data folder. Could you tell me where can i download theses files and how to prepare the data? Thanks a lot.

**Comment by yxKryptonite** [comment]
Hi, missing files `matterport_category_mappings.tsv` and `object_norm_inv_perplexity.npy` are uploaded. Sorry for any inconvenience!

For other dataset folders, you can access them at official website of [HM3DSem](https://aihabitat.org/datasets/hm3d-semantics/).

**Comment by zwhy66** [comment]
> 感谢您的出色工作。我在准备数据时遇到了一些麻烦。我不知道在哪里可以下载这些文件（matterport_category_mappings.tsv 和 object_norm_inv_perplexity.npy）。我对versioned_data文件夹中的文件感到困惑。您能告诉我在哪里可以下载这些文件以及如何准备数据吗？多谢。

你好，请问你完成openfmnav的复现了吗，我想问您和您讨论一下问题。不知是否可以。vx：17303470305
